version: '2'

services:

  dockermignis:
    build: .
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "host"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
     - HTTP_USER=user
     - HTTP_PASS=pass
